# =============================================================================
# NetworkMemories — MGO2 Gateway — Apache VHost
# =============================================================================
<VirtualHost *:80>
    ServerName mg.mgo.konami.com
    ServerAlias *.konami.net *.mgo.konami.com
    DocumentRoot /var/www/html

    <Directory /var/www/html>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog  /var/log/apache2/nomad-error.log
    CustomLog /var/log/apache2/nomad-access.log combined
</VirtualHost>
